### PR TITLE
Update 3.md

### PR DESCRIPTION
**Pull request by annegentle**

### CODE REVIEW

**Comment by annegentle** [comment]
@aroach Can you take a look? What's the correct way to do image references?

**Comment by aroach** [comment]
@annegentle this should work: Figure

**Comment by annegentle** [comment]
@aroach Thanks for the quick response -- what is the `<labid>` value?

**Comment by aroach** [comment]
@annegentle it's what you defined here: https://github.com/CiscoDevNet/metacloud-learning-labs/blob/master/labs/heat/heat.json#L2

**Pull request merged**
